name: Issue Operations

on:
  issues:
    types:
      - opened
      - edited
      - labeled

jobs:
  handle-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Pulumi CLI
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin

      - name: Login to Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login

      - name: Select Pulumi Stack
        run: |
          pulumi stack select dev

      - name: Extract MOTD from Issue Body
        id: extract-motd
        if: contains(github.event.label.name, 'update-motd')
        run: |
          echo "Extracting MOTD from issue body..."
          MOTD=$(echo "${{ github.event.issue.body }}" | sed -n 's/^### MOTD\n//p')
          if [ -z "$MOTD" ]; then
            echo "Error: MOTD not found in issue body. Ensure the issue body contains the MOTD value."
            exit 1
          fi
          echo "motd=$MOTD" >> $GITHUB_ENV

      - name: Update MOTD using Pulumi CLI
        if: contains(github.event.label.name, 'update-motd')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Updating MOTD using Pulumi CLI..."
          echo "MOTD: $MOTD"
          pulumi config set pulumi_ts:motd "$MOTD" --cwd .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add Pulumi.dev.yaml
          git commit -m "Update MOTD to $MOTD"
          git push

      - name: Trigger Push Workflow
        if: contains(github.event.label.name, 'deploy')
        uses: actions/github-script@v6
        with:
          script: |
            console.log("Triggering push.yml workflow...");
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "push.yml",
              ref: "main"
            });

      - name: Trigger Destroy Workflow
        if: contains(github.event.label.name, 'destroy')
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "destroy.yml",
              ref: "main"
            });

      - name: Comment on the Issue
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const commentBody = "The workflow has completed successfully!";
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: commentBody,
            });